import type { ItemInventario } from '../types/types'

export const INVENTARIO: ItemInventario[] = [
  {
    id: 1,
    marca: 'Dell',
    modelo: 'OptiPlex 3090',
    noSerie: 'DL3090-CHX-001',
    descripcion: 'PC escritorio para área administrativa',
    categoria: 'equipo_computo',
    departamento: 'Administración',
    estado: 'bueno',
    clues: 'CSIMB000035',
  },
  {
    id: 2,
    marca: 'HP',
    modelo: 'ProBook 450 G9',
    noSerie: 'HP450G9-CHX-002',
    descripcion: 'Laptop para trabajo en campo',
    categoria: 'equipo_computo',
    departamento: 'Dirección',
    estado: 'excelente',
    clues: 'CSIMB000035',
  },
  {
    id: 3,
    marca: 'Lenovo',
    modelo: 'ThinkCentre M70s',
    noSerie: 'LNV70S-CHX-003',
    descripcion: 'PC escritorio recepción',
    categoria: 'equipo_computo',
    departamento: 'Enfermería',
    estado: 'malo',
    clues: 'CSIMB000303',
  },
  {
    id: 4,
    marca: 'HP',
    modelo: 'Pavilion 14',
    noSerie: 'HPPAV14-CHX-004',
    descripcion: 'Laptop consulta médica',
    categoria: 'equipo_computo',
    departamento: 'Medicina General',
    estado: 'bueno',
    clues: 'CSIMB000076',
  },
  {
    id: 5,
    marca: 'Acer',
    modelo: 'Aspire TC-895',
    noSerie: 'ACRTC895-CHX-005',
    descripcion: 'PC escritorio laboratorio',
    categoria: 'equipo_computo',
    departamento: 'Laboratorio',
    estado: 'muy_malo',
    clues: 'CSIMB000052',
  },
  {
    id: 6,
    marca: 'Cisco',
    modelo: 'SG110-16',
    noSerie: 'CSC110-CHX-006',
    descripcion: 'Switch 16 puertos área administrativa',
    categoria: 'equipo_red',
    departamento: 'Soporte Técnico',
    estado: 'excelente',
    clues: 'CSIMB000035',
  },
  {
    id: 7,
    marca: 'TP-Link',
    modelo: 'TL-WR940N',
    noSerie: 'TPL940N-CHX-007',
    descripcion: 'Router inalámbrico sala espera',
    categoria: 'equipo_red',
    departamento: 'Soporte Técnico',
    estado: 'bueno',
    clues: 'CSIMB000303',
  },
  {
    id: 8,
    marca: 'Ubiquiti',
    modelo: 'UniFi AP AC Lite',
    noSerie: 'UBI-ACLITE-008',
    descripcion: 'Punto de acceso WiFi piso 2',
    categoria: 'equipo_red',
    departamento: 'Soporte Técnico',
    estado: 'bueno',
    clues: 'CSIMB000035',
  },
  {
    id: 9,
    marca: 'HP',
    modelo: '664XL Negro',
    noSerie: 'N/A',
    descripcion: 'Cartucho tinta negra alta capacidad',
    categoria: 'consumible_tinta',
    departamento: 'Administración',
    estado: 'bueno',
    clues: 'CSIMB000035',
  },
  {
    id: 10,
    marca: 'Epson',
    modelo: 'T544 Cyan',
    noSerie: 'N/A',
    descripcion: 'Cartucho tinta cian impresora L3210',
    categoria: 'consumible_tinta',
    departamento: 'Dirección',
    estado: 'bueno',
    clues: 'CSIMB000076',
  },
  {
    id: 11,
    marca: 'HP',
    modelo: 'CF283A',
    noSerie: 'N/A',
    descripcion: 'Tóner LaserJet Pro M125',
    categoria: 'consumible_toner',
    departamento: 'Administración',
    estado: 'bueno',
    clues: 'CSIMB000303',
  },
  {
    id: 12,
    marca: 'Brother',
    modelo: 'TN-1060',
    noSerie: 'N/A',
    descripcion: 'Tóner impresora HL-1200',
    categoria: 'consumible_toner',
    departamento: 'Enfermería',
    estado: 'malo',
    clues: 'CSIMB000052',
  },
  {
    id: 13,
    marca: 'Kingston',
    modelo: 'DDR4 8GB 3200MHz',
    noSerie: 'KNG-RAM-013',
    descripcion: 'Memoria RAM para actualización equipos',
    categoria: 'refaccion',
    departamento: 'Soporte Técnico',
    estado: 'excelente',
    clues: 'CSIMB000035',
  },
  {
    id: 14,
    marca: 'WD',
    modelo: 'Blue 1TB SSD',
    noSerie: 'WD1TBSSD-014',
    descripcion: 'Disco duro reemplazo laptop dirección',
    categoria: 'refaccion',
    departamento: 'Soporte Técnico',
    estado: 'excelente',
    clues: 'CSIMB000204',
  },
]
